### ISSUE TITLE
jsdom v15 to v16

### ISSUE THREAD

**Issue by huihuimoe** [huihuimoe/pt-autorss#105]
https://github.com/jsdom/jsdom/blob/master/Changelog.md#1600

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!

**Comment by huihuimoe** [comment]
[d8d8831](https://github.com/huihuimoe/pt-autorss/commit/d8d88311d184d0d031b2fd225fca0e97ac74949c)
Close
