### ISSUE TITLE
求支持qbittorrent  api方式

### ISSUE THREAD

**Issue by wxlg1117** [huihuimoe/pt-autorss#25]
RT
好像有现成的qbittorrent-api 或者node-qbittorrent 可参考，求楼主集成...

**Comment by wxlg1117** [comment]
emmm,这么快就看到楼主集成了，请问这么配置config.ts for qbittorrent啊？

**Comment by huihuimoe** [comment]
还没写(
我要改下基础库，原本的库没有方便的可以自定义的选项
晚点我测试完再推上来

发件人: wxlg1117 <notifications@github.com>
发送时间: Thursday, March 28, 2019 18:33
收件人: huihuimoe/pt-autorss <pt-autorss@noreply.github.com>
抄送: 灰灰 <0w0@loli.pet>; Assign <assign@noreply.github.com>
主题: Re: [huihuimoe/pt-autorss] 求支持qbittorrent api方式 (#25)


emmm,这么快就看到楼主集成了，请问这么配置config.ts for qbittorrent啊？

**Comment by huihuimoe** [comment]
have a try?

**Comment by wxlg1117** [comment]
还没呢，待会到家测试了给反馈
