### ISSUE TITLE
Pushing torrent to qBittorrent using qBittorrent API 失败...

### ISSUE THREAD

**Issue by wxlg1117** [huihuimoe/pt-autorss#26]
配置文件config.ts：

import DelugeInitializer from './plugins/delugeRPC'
import qBittorrentInitializer from './plugins/qBittorrent'
import rTorrentInitializer from './plugins/rTorrent'
import TransmissionInitializer from './plugins/transmission'

// some variable
const savePath = '/root/Torrents'
const qBittorrentWatchPath = '/mnt/qBittorrent/watch'
const DelugeWithMaxUp50M = DelugeInitializer('http://127.0.0.1:8112/', 'deluge', {
  max_upload_speed: 51200,
})
const qBittorrent = qBittorrentInitializer(
  {
    host: 'http://127.0.0.1:8080',
    password: 'root',
    username: 'admin',
  },
  {
    dlLimit: 10000000, // Bytes/s
    skip_checking: 'false',
    upLimit: 10000000,
  },
)
const rTorrent = rTorrentInitializer('127.0.0.1:1088')
const Transmission = TransmissionInitializer({
  password: 'admin',
  username: 'admin',
})

// default settings
export const global = {
  headers: {
    accept: 'text/html,application/xhtml+xml,application/xml',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US',
    'cache-control': 'max-age=0',
    dnt: '1',
    'user-agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
      'Chrome/72.0.3626.119 Safari/537.36',
  },
  interval: 30000,
  timeout: 10000,
}

/*
 * tips:
 * press F12 and type `document.cookie` in  console to get cookie
 */
// download all torrents of both two url and push to rtorrent every 30s
import MT from './sites/mteam'
const mt = new MT({
  config: {
    cookie: 'MT COOKIE ',
    url: ['https://tp.m-team.cc/adult.php'],
  },
  filter(s) {
    if (s.isSticky) return false
    //if ((s.isFree || s.is2xfree) && s.size < 10) return true
    if ((s.isNew) && s.size <10) return true  
  },
  async success(s) {
    // save to path
    //await this.download(s).to(qBittorrentWatchPath)
    // using qBittorrent API
    const file = await this.download(s).to(savePath)
    await qBittorrent(file, {
      category: 'TTG',
      //savepath: '/opt/Movies',
    })
  },
})

let configs: import('./libs/helper').ObjectMap<import('./typings/application').IApplication>
configs = {
  mt,
}

export default configs

npm start ：

3/29/2019, 11:25:24 AM  -  Start task  mt
3/29/2019, 11:25:28 AM  -  Detected new torrents on mt - [285414]
3/29/2019, 11:25:28 AM  -  Excute success function with mt 285414
3/29/2019, 11:25:28 AM  -  Downloading torrent 285414 from mt ...
3/29/2019, 11:25:29 AM  -  Download torrent 285414 from mt completed. Save to /root/Torrents/mt - 285414.torrent.
3/29/2019, 11:25:29 AM  -  Pushing mt - 285414.torrent to qBittorrent using qBittorrent API...
3/29/2019, 11:25:29 AM  -  Complete task mt, wait for 600000ms

/root/Torrents/下存在mt - 285414.torrent；
http:// 127.0.0.1:8080，admin用户密码root登录没问题；
push也没提示失败，但是qb里面实际没有出现该种子种子

大佬push过程中哪可以看到日志好用来判断哪出问题了？

**Comment by huihuimoe** [comment]
估计是掉认证了没识别出来，不知道为什么这个库调用失败了也没有报错，先这样加个patch，之后我再看看怎么改吧

**Comment by wxlg1117** [comment]
这次错误出来了，无法登录qb：
3/29/2019, 12:14:15 PM  -  /root/pt-autorss/node_modules/qbittorrent-api/src/qbt.js:266
      callback(new Error('Login failed with username: ' + username));
               ^
3/29/2019, 12:14:15 PM  -  Error: Login failed with username: admin
    at Object.callback (/root/pt-autorss/node_modules/qbittorrent-api/src/qbt.js:266:16)
    at Request.<anonymous> (/root/pt-autorss/node_modules/async/dist/async.js:2271:31)
    at Request._callback (/root/pt-autorss/node_modules/async/dist/async.js:969:16)
    at Request.self.callback (/root/pt-autorss/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/pt-autorss/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/pt-autorss/node_modules/request/request.js:1083:12)

**Comment by huihuimoe** [comment]
确保用户名密码正确，host最后不带`/`(
其他的我也不知道了(

**Comment by wxlg1117** [comment]
刚发现了配置文件里面的qb的host 不能用127.0.0.1，换成我的盒子ip就好了，虽然我验证过 我的服务器http://127.0.0.1:8080和http://服务器ip:8080都能登录的
