### ISSUE TITLE
推送到远程deluge失败

### ISSUE THREAD

**Issue by lanxuewsr** [huihuimoe/pt-autorss#38]
配置文件：
import DelugeInitializer from './plugins/delugeRPC'
import qBittorrentInitializer from './plugins/qBittorrent'
import rTorrentInitializer from './plugins/rTorrent'
import TransmissionInitializer from './plugins/transmission'

// some variable
const savePath = '/opt/torrents'
const Deluge = DelugeInitializer('http://206.189.112.183:8112', 'deluge',)

// default settings
export const global = {
  headers: {
    accept: 'text/html,application/xhtml+xml,application/xml',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US',
    'cache-control': 'max-age=0',
    dnt: '1',
    'user-agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
      'Chrome/72.0.3626.119 Safari/537.36',
  },
  interval: 95000,
  timeout: 15000,
}

// mt uploader < 5, downloader > 13, every 95s
import MTEAM from './sites/mteam'
const mt = new MTEAM({
  config: {
    cookie: 'cookie',
    interval: 95000,
    url: 'https://tp.m-team.cc/torrents.php',
  },
  filter(s) {
    if (s.seeder < 5 && s.leecher > 13) return true
  },
  async success(s) {
    await this.download(s)
      .to(savePath)
      .then(Deluge)
  },
})

let configs: import('./libs/helper').ObjectMap<import('./typings/application').IApplication>
configs = {
  mt,
}

export default configs

运行报错：
 # npm start

> pt-autorss@4.0.0 start /root/pt/pt-autorss
> ts-node -T .

2019-4-23 19:11:15  -  Start task  mt
2019-4-23 19:11:21  -  Detected new torrents on mt - [289501,289780,289730]
2019-4-23 19:11:21  -  Excute success function with mt 289501
2019-4-23 19:11:21  -  Downloading torrent 289501 from mt ...
2019-4-23 19:11:24  -  Download torrent 289501 from mt completed. Save to /opt/torrents/mt - 289501.torrent.
2019-4-23 19:11:24  -  Pushing mt - 289501.torrent to deluge with delugeRPC...
2019-4-23 19:11:24  -  Error  mt  -
2019-4-23 19:11:24  -  undefined

大佬，我之前推送到本机能正常。现在推送到远程机器上的deluge里，总是报错。麻烦大佬帮我看看这个报错具体什么原因，非常感谢！^_^

**Comment by huihuimoe** [comment]
试下新的？
以及网站密码泄露了，建议修改密码

**Comment by lanxuewsr** [comment]
大佬，尝试了下新版本，还是会报错，但是错误信息变了：

npm start

> pt-autorss@4.0.0 start /root/pt/pt-autorss
> ts-node -T .

2019-4-23 21:43:33  -  Start task  mt
2019-4-23 21:43:40  -  Detected new torrents on mt - [289867,289501,289846,289730]
2019-4-23 21:43:40  -  Excute success function with mt 289867
2019-4-23 21:43:40  -  Downloading torrent 289867 from mt ...
2019-4-23 21:43:41  -  Download torrent 289867 from mt completed. Save to /opt/torrents/mt - 289867.torrent.
2019-4-23 21:43:41  -  Pushing mt - 289867.torrent to deluge with delugeRPC...
2019-4-23 21:43:41  -  Error  mt  - got  400
2019-4-23 21:43:41  -  Error: Request failed with status code 400
    at createError (/root/pt/pt-autorss/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/pt/pt-autorss/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/pt/pt-autorss/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by huihuimoe** [comment]
更新下依赖再试试？

**Comment by lanxuewsr** [comment]
大佬，我刚才试了下还是会报错。
我是删了文件夹，重新git clone的，看了下package.json应该是新的了，还需要其他别的操作吗？

![061](https://user-images.githubusercontent.com/10062265/56595858-fb71bd80-6621-11e9-81ab-c4f1bd1b9cec.PNG)

![062](https://user-images.githubusercontent.com/10062265/56595869-0298cb80-6622-11e9-8cc2-da6ce00a8c86.PNG)

**Comment by huihuimoe** [comment]
这次我测试过了，应该是OK了 ORZ

**Comment by lanxuewsr** [comment]
我这也推送成功了！非常感谢大佬！(づ｡◕ᴗᴗ◕｡)づ
